---
apiVersion: v1
kind: Service
metadata:
 name: guides
 labels:
   app: guides
spec:
 type: NodePort
 ports:
 - port: 8080
   nodePort: 32718
   protocol: TCP
 selector:
   app: guides
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: guides-deploy
spec:
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: guides
    spec: 
      containers:
      - name: guides-pod
        image: artyomgrishchenko/guides:1.0.0-0-rc
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: config
              key: environment
        - name: MONGO_ENABLED
          value: "true"