# Build stage
FROM microsoft/dotnet:2.1-sdk AS build

# set working directory
WORKDIR /app

# Restore
COPY src/Interface/Wexxle.Guide.Interface.csproj ./src/Interface/
RUN dotnet restore src/Interface/Wexxle.Guide.Interface.csproj
COPY src/Service/Wexxle.Guide.Service.csproj ./src/Service/
RUN dotnet restore src/Service/Wexxle.Guide.Service.csproj
COPY src/Client/Wexxle.Guide.Client.csproj ./src/Client/
RUN dotnet restore src/Client/Wexxle.Guide.Client.csproj
COPY src/Process/Process.csproj ./src/Process/
RUN dotnet restore src/Process/Process.csproj
COPY test/Service.Test/Service.Test.csproj ./test/Service.Test/
RUN dotnet restore test/Service.Test/Service.Test.csproj
COPY test/Client.Test/Client.Test.csproj ./test/Client.Test/
RUN dotnet restore test/Client.Test/Client.Test.csproj

# Copy src
COPY . .

# Test
##RUN dotnet test test/Service.Test/Service.Test.csproj \
##    && dotnet test test/Client.Test/Client.Test.csproj
