version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    command: ${TEST_CMD:-bash -c "dotnet test Test/Service.Test/Service.Test.csproj && dotnet test Test/Client.Test/Client.Test.csproj"}
    depends_on:
      - mongo
    environment:
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_COLLECTION=guides
      - MONGO_SERVICE_URI=mongodb://mongo:27017/wexxle
  mongo:
    image: mongo:latest

